"""The v1 fitting-engine public surface."""

from veridist.engine.checkpoint import (
    CheckpointCommitUncertain,
    CheckpointRecord,
    CheckpointStore,
    InMemoryCheckpointStore,
)
from veridist.engine.data_source import (
    CheckpointMetadata,
    DataSourceCapabilityError,
    DataSourceMetadata,
    Replayability,
    SpoolPolicy,
    plan_passes,
)
from veridist.engine.delivery import (
    AdapterCapabilities,
    AdapterKind,
    BoundedChunkBuffer,
    BufferedChunk,
    ChunkEnvelope,
    DeliveryContractError,
    DeliveryValidator,
    OrderingGuarantee,
)
from veridist.engine.errors import EngineContractError, FailureCode
from veridist.engine.outcome import (
    CompleteOutcome,
    Coverage,
    ExecutionOutcome,
    FailedOutcome,
    FailureRecord,
    FailureStage,
    KnownCoverage,
    KnownExtent,
    OutcomeStatus,
    PartialOutcome,
    RowRange,
    UnknownMissingRanges,
    classify_execution_outcome,
)
from veridist.engine.pass_budget import PassBudgetError, PassEnforcer
from veridist.engine.resume import (
    PublicResumeMetadata,
    ResumedCheckpoint,
    ResumeExpectation,
    resume_checkpoint,
)
from veridist.engine.retry import (
    EffectStatus,
    IdempotentSink,
    PureReducer,
    SinkResult,
    apply_pure_update,
    apply_sink_update,
)

__all__ = [
    "AdapterCapabilities",
    "AdapterKind",
    "BoundedChunkBuffer",
    "BufferedChunk",
    "CheckpointMetadata",
    "CheckpointCommitUncertain",
    "CheckpointRecord",
    "CheckpointStore",
    "ChunkEnvelope",
    "CompleteOutcome",
    "Coverage",
    "DataSourceCapabilityError",
    "DataSourceMetadata",
    "DeliveryContractError",
    "DeliveryValidator",
    "EngineContractError",
    "EffectStatus",
    "FailureCode",
    "ExecutionOutcome",
    "FailedOutcome",
    "FailureRecord",
    "FailureStage",
    "IdempotentSink",
    "InMemoryCheckpointStore",
    "OrderingGuarantee",
    "KnownCoverage",
    "KnownExtent",
    "OutcomeStatus",
    "PassBudgetError",
    "PassEnforcer",
    "PartialOutcome",
    "PureReducer",
    "PublicResumeMetadata",
    "Replayability",
    "RowRange",
    "ResumedCheckpoint",
    "ResumeExpectation",
    "SpoolPolicy",
    "SinkResult",
    "UnknownMissingRanges",
    "apply_pure_update",
    "apply_sink_update",
    "classify_execution_outcome",
    "plan_passes",
    "resume_checkpoint",
]
