{% set name = "veridist" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alisadeghiaghili/veridist/releases/download/v{{ version }}/veridist-{{ version }}.tar.gz
  sha256: 020d463ef3174638ffceb802758a8a6bff1117cdb20ff7b41aaa1c538a2fb07b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools >=77
  run:
    - numpy >=1.26,<3
    - python >=3.11

test:
  imports:
    - veridist

about:
  home: https://github.com/alisadeghiaghili/veridist
  license: BUSL-1.1
  license_file: LICENSE
  summary: Evidence-first distribution fitting with explicit execution contracts

extra:
  recipe-maintainers:
    - alisadeghiaghili
